baseURL = "https://wellarchitectedlabs.com/"
defaultContentLanguage = "en"
theme = "learn"

[languages]
  [languages.en]
    languageName = 'English'
    title = 'AWS Well-Architected Labs'
    weight = 1
  [languages.es]
    languageName = 'Espa√±ol'
    title = 'AWS Well-Architected Labs'
    weight = 2
[params]
themeVariant = "walabs"
disableShortcutsTitle = true

# Order sections in menu by "weight" or "title". Default to "weight"
ordersectionsby = "weight"
    # Weights by pillar:
    # 1000 - Operational Excellence
    # 2000 - Security
    # 3000 - Reliability
    # 4000 - Performance Efficiency
    # 5000 - Cost Optimization
    # 6000 - Well Architected Tool
    # 7000 - Well Architected Partners
    # 8000 - Contributing Guide
editURL = "https://github.com/awslabs/aws-well-architected-labs/blob/master/content/"
description = "Hands on labs and real world design scenarios for Well-Architected workloads"
author = "Well-Architected Team"
showVisitedLinks = true
# Hide Next and Previous page buttons normally displayed full height beside content
disableNextPrev = true
#AWS custom params
base_github_url = "https://github.com/awslabs/aws-well-architected-labs/tree/master/"
base_raw_github_url = "https://raw.githubusercontent.com/awslabs/aws-well-architected-labs/master/"
#{{% siteparam "base_github_url" %}}


[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
section = ["HTML","RSS"]

# Menu shortcuts on left side
[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>&nbsp;&nbsp;Contributing (GitHub)"
url = "https://github.com/awslabs/aws-well-architected-labs/blob/master/CONTRIBUTING.md"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-rss'></i>&nbsp;&nbsp;Labs RSS Feed"
url = "/index.xml"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i>&nbsp;&nbsp;Amazon Free Tier"
url = "https://aws.amazon.com/free/"
weight = 20
